[package]
name = "graph1_wasm_demo"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = false
opt-level = 3  # Maximum performance
lto = true
codegen-units = 1  # Better optimization (slower compile)

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O3", "--enable-simd", "--enable-bulk-memory", "--strip-debug"]


[dependencies]
wasm-bindgen = "0.2.106"
web-sys = { version = "0.3.83", features = ["console"] }
graph1 = { path = "../graph1" }

console_error_panic_hook = "0.1.7"

[lib]
crate-type = ["cdylib", "rlib"]
