#!/bin/bash

# Make sure our custom web files are copied
cp -R ./web-files/* ./pkg/

# Kill the previous PPython3 webserver, if any
#PID=$(ps aux | grep "python3 -m http.server 8080 --directory ./pkg/" | grep -v grep | awk '{print $2}')
PID=$(ps aux | grep "python3 graph1_demo_serve.py" | grep -v grep | awk '{print $2}')

if [[ -n "$PID" ]]; then
  echo "Killing the old Python3 webserver process $PID"
  kill -15 $PID
else
  echo "No Python3 webserver process found"
fi

# Run a new Python3 webserver
echo "Starting a Python3 webserver for our WASM"
#python3 -m http.server 8080 --directory ./pkg/
python3 graph1_demo_serve.py
